version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
          name: update pip
          command: pip install --upgrade pip
      - run:
          name: awsebcli
          command: pip install awsebcli
      - run:
          name: testing ecxec
          command: bash ./ci/test.sh
      - run:
          name: show test
          command: |
            sed -i'.bak' "s/${TEST}/${CI_TEST}/g" ./sample-page/.env
            sed -i'.bak' "s/${TEST2}/${CI_TEST}/g" ./sample-page/.env
            
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development