version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
            name: awsebcli
            command: pip install awsebcli
      - run: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install nodejs
      - run:
          name: Deploying laod
          command: bash ./ci/deploy-${CIRCLE_BRANCH}.sh

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development