version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
          name: update pip
          command: pip install --upgrade pip
      - run:
          name: cypress run
          command: bash .cypress/exec.sh -e local -i -a
      - run:
          name: testing ecxec
          command: bash ./ci/test.sh
      - run:
          name: show testING
          command: cat ./sample-page/.env;
            
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development