version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
            name: awsebcli
            command: pip install awsebcli
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Deploying laod
          command: bash ./ci/deploy-${CIRCLE_BRANCH}.sh

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development