version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
            name: awsebcli
            command: pip install awsebcli
      - run:
            name: Install dependencies
            command: |
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
              source ~/.bashrc
              nvm install v6.11.1
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"            - run: nvm --version
      - run:
          name: Deploying laod
          command: bash ./ci/deploy-${CIRCLE_BRANCH}.sh

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development