version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: install urllib3
          command: pip install urllib3==1.21.1
      - run:
            name: awsebcli
            command: pip install awsebcli
      - run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - run: sudo apt update && sudo apt install yarn
      - run:
          name: Deploying laod
          command: bash ./ci/deploy-${CIRCLE_BRANCH}.sh

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - development