name: CI RUN DEV

on: 
  push:
    branches: 
      - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name : pwd
      run: pwd
    - name : ls -la
      run: ls -la   
      
      
